import type { Metadata } from "next";
import { MapProvider } from "@/context/MapContext";
import { UserProvider } from "@/context/UserContext";
import '../style/global.scss'

export const metadata: Metadata = {
  title: "AuroraMap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <MapProvider>
            {children}
          </MapProvider>
        </UserProvider>
      </body>
    </html>
  );
}
